title: Flipping the Coins, Rolling the Dice
hero_image: images/banner.png
description:
version: 4
listed: false
copyedit: false
last_tested: "2018-12-06"
steps:
  - title: Introduction
  - title: Create a coin flipper
  - title: Make the dice
  - title: Build an interface
  - title: "Challenge: impossible dice"
    challenge: true
