---
title: Coin & dice
hero_image: images/banner.png
description:
version: 4
listed: true
copyedit: true
last_tested: '2018-12-06'
steps:
- title: Introduction
  completion: engaged
- title: Create a coin flipper
- title: Make the dice
  completion: internal
- title: Build an interface
- title: 'Challenge: impossible dice'
  challenge: true
