---
title: Coin & dice
hero_image: images/banner.png
description: 
version: 4
listed: true
copyedit: true
last_tested: '2018-12-06'
steps:
- title: Introduction
- title: Create a coin flipper
- title: Make the dice
  completion:
  - engaged
- title: Build an interface
  completion:
  - internal
- title: 'Challenge: impossible dice'
  challenge: true
